### ISSUE TITLE
PHP Fatal Error on PHP7

### ISSUE THREAD

**Issue by brdcg** [bombcheck/FB.Switch#10]
when running FB.Switch on a newly installed apache2/php7 host, editing the config produces:
` PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function config_save()` depending on which action is triggered, the source is the relevant file (e.g. edit_group.php)
I was able to workaroud it by changing the 
`config_save();` instruction to `config_save($CONFIG_FILENAME, $xml);`
Maybe you can check this?

**Comment by bombcheck** [comment]
I know that someone used FB.Switch on PHP7 without problems... But here it seems that the issue has to do with the way the `config_save()`-function implements optional paramters... Will have a look into this.

**Comment by bombcheck** [comment]
(Hopefully) fixed here: https://github.com/bombcheck/FB.Switch/commit/eda1d03591c2e52faaa92d419d584783f3237666

Can you try it?

**Comment by brdcg** [comment]
Looks good to me. I am not very familiar with github so i manually changed the file. 
works for me - thank you for the quick response.
Dankeschön :)

**Comment by bombcheck** [comment]
You're welcome. :)
Will close this issue. Feel free to re-open if the problem still persists.
