### ISSUE TITLE
Startanimation deaktivierbar machen

### ISSUE THREAD

**Issue by obakuhl** [bombcheck/FB.Switch#2]
Hallo zusammen,
das Projekt ist wirklich super, nach einigen recherchen bin ich auf es gestoßen. Hab jetzt sehr lange die mentox Version verwendet, mir aber immer vorgenommen die selber mal weiter aufzubohren und siehe da, das haben bereits fleißige gemacht. Ingesamt gefällt mir die WebApp super, nur die Startanimation gefällt mir nicht wirklich, kann man die ausblenden, oder hat die einen besonderen Hintergrund?

Was mich natürlich ingesamt etwas stört sind die doch sehr an iOS angelehnte Bedienelemente, aber das ist wieder ein Thema für sich. Diese drehenden Ringe wirken modern, das geht schon in die richtige Richtung. :)

**Comment by bombcheck** [comment]
Hi,

freut mich zu hören das mein Projekt Verwendung findet. :)
Klar wäre das kein Problem die Animation abschaltbar zu machen. Aber irgendwas sollte beim laden schon angezeigt werden, weil die App braucht halt ne gewisse Zeit zum laden. Und ein weißer Bildschirm sieht ja nicht so doll aus...
Stört dich die Animation oder das Logo?

Gruß

**Comment by obakuhl** [comment]
Das stimmt natürlich, also es geht mir mehr um die Animation. Vielleicht kann man das ganze sogar so machen, das da steht um was es sich handelt. Also dieser "Vorhang" der sich quasi öffnet gefällt mir persönlich jetzt nicht.
OT: Was ich noch fragen wollte, gibt es eine Liste mit untersützten geräten? Ich dachte nämlich daran auch daran Tempertursensoren bzw. Feuchtigkeitssensoren einzubauen. Zu erst dachte ich da an Bastelversion mit dem raspberry und verschiedenen Sensoren die über die Netzwerkschnittstelle ausgelesen werden können, aber wenn es preiswerte sensoren die im 433 MHz Kanal funken kann man auch das in Betracht ziehen.

Viele Grüße Ben

**Comment by bombcheck** [comment]
Hi,

also diesen Vorhang könnte man schaltbar machen. Genau wie der blaue Kreisel im Startbildschirm. Ggf. austauschen gegen den Programmnamen und die Programmversion...

Also es sind alle Geräte kompatibel, die auch mit der Mentox-Version liefen. Von den 433MHz-Geräten sind mir nur Schalter bekannt. Die Teile haben ja keinen Rückkanal, daher gibts auch keine Sensoren davon (soweit mir bekannt).
Allerdings kannst du in meiner Version noch FritzDect200-Geräte einbinden (in Verbindung mit einer kompatiblen FritzBox). Außerdem werden MiLight-RGBW-Lampen unterstützt (gibt es auch unter diversen anderen Handelsnamen).

Gruß

**Comment by obakuhl** [comment]
Das wäre doch nicht schlecht.
Alles klar vielen Dank. Was ich mich schon länger gefragt habe, eine einbindung von einem 868 mhz gateway ist nicht möglich oder? Dann könnte man auch Heizkörperregler und eben Thermometer einbauen. Aber ein paralleler Betrieb macht soweiso kaum sinn oder?

**Comment by bombcheck** [comment]
Habe unter "Design" in der Konfig der DEV-Branch ein Setting integriert, um die Start-Animation abschalten zu können. Es wird statt dessen ein statisches Bild angezeigt.

Wünsche allen ein Frohes Fest!

Commit 58603044bfeac1278e43638a09e315d65a97fb83

**Comment by obakuhl** [comment]
Danke, das schaut schon super aus. Den Vorhang kann man nicht auch deaktivieren? Quasi das die Website einfach erscheint?

**Comment by bombcheck** [comment]
Ist doch nun so. Wenn die Splash-Animation deaktiviert ist wird nur ein statisches Bild angezeigt und dann erscheint das Interface irgendwann. Kein Ladekreisel und kein Vorhang.

**Comment by obakuhl** [comment]
Hatte einen Berechtigungsfehler, jetzt passt alles. Schaut wirklich super aus.
Edit: Auf der mobilen Seite taucht das Schaltersymbol kurz auf, obwohl die Einstellung abgewählt ist (Win 10 mobile, Edge).

**Comment by bombcheck** [comment]
Ja, es taucht während der Ladezeit ein statisches Bild auf bevor dann das Interface erscheint. Oder meinst du etwas anderes?
