### ISSUE TITLE
Sounds deaktivieren

### ISSUE THREAD

**Issue by TribuneX** [bombcheck/FB.Switch#5]
Gibt es eine Einstellung um die Sounds zu deaktivieren?

**Comment by bombcheck** [comment]
Nein, gibt es derzeit nicht. Wäre aber kein Problem das zu integrieren... :)

**Comment by obakuhl** [comment]
Ich wäre stark dafür, wenn man diesen deaktivieren könnte.

**Comment by bombcheck** [comment]
Stimmt, ist nicht ganz unpraktisch.
Hab es in der DEV-Branch eingepflegt. Probiert es mal bitte aus. 😄 

Commit 66290bc72ee0f94a58f8d7c7d3529efa13b3e6e9
