### ISSUE TITLE
PHP7 error

### ISSUE THREAD

**Issue by TribuneX** [bombcheck/FB.Switch#6]
Hi,

ich habe meinen Server gerade auf PHP7 aktualisiert. nginx meldet seitdem:
`
FastCGI sent in stderr: "PHP message: PHP Fatal error:  Redefinition of parameter $timerday in /var/www/connair/timer.php on line 296" while reading response header from upstream, client: 192.168.178.23, server: mydomain.net, request: "GET /connair/index.php?timerrun=1 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "192.168.178.23"
`

Gibt es hierfür eine Lösung?

**Comment by bombcheck** [comment]
Hm hab kein PHP7 im Einsatz aber eine Idee was es sein könnte... Schau ich mir nachher einmal an.

**Comment by bombcheck** [comment]
Da gab es eine obsolete Funktion send_timer() in der timer.php, welche die Variable $timerday zwei mal in den zu übergebenden Parametern hatte.
Habe die Funktion in der DEV-Branch mit commit 1c64e2fb3a68f7c0c624a0681940fc77af25e030 entfernt.

**Comment by TribuneX** [comment]
Danke! Funktioniert. Der Fehler tritt nicht weiter auf.

**Comment by bombcheck** [comment]
Perfekt, habe den Fix dann auch in die Master-Branch eingepflegt.
commit 46359385b609f8bcb89b3e78b37803366fe6df08
